run:
  skip-dirs:
    - bin
    - .github
    - tools

linters-settings:
  govet:
    check-shadowing: true

linters:
  enable-all: true
  disable:
    - cyclop
    - dogsled
    - dupl
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - funlen
    - gocognit
    - godox
    - gomnd
    - interfacer
    - ireturn
    - maintidx
    - nlreturn
    - nosnakecase
    - paralleltest
    - testpackage
    - wsl
    - depguard
    - perfsprint
    - scopelint
    - golint
    - structcheck
    - maligned
    - ifshort
    - varcheck
    - deadcode

issues:
  exclude-rules:
    - text: "shadow: declaration of \"err\""
      linters: ["govet"]
    - text: "use of `fmt.Print"
      linters: ["forbidigo"]
    - text: "is too short for the scope of its usage"
      linters: ["varnamelen"]
    - text: "has complex nested blocks"
      linters: ["nestif"]
