run:
  skip-dirs:
    - bin
    - .github
    - tools

linters-settings:
  govet:
    check-shadowing: true

linters:
  enable:
    - deadcode
    - errcheck
    - errorlint
    - exportloopref
    - forcetypeassert
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - misspell
    - noctx
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign

issues:
  exclude-rules:
    # Exclude shadow checking on the variable named err
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
    # Exclude magic number detection
    - text: "mnd: Magic number"
      linters:
        - gomnd
