name: Go
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ./go.mod

    - run: make bootstrap-tools
    - run: make lint
    - run: make cover

    - uses: k1LoW/octocov-action@v1
